language: android
jdk: oraclejdk7

android:
  components:
    - tools
    
    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23
    
    # Additional components
    - extra-android-support

before_install:
  - chmod +x gradlew
